/* Mein MiniJavaExp Code aus A1 zum Testen:
final int c = 1; int v = 2; print(c+v*v*v);
*/

//PARSER FÜR MINIJAVAEXP
PARSER_BEGIN(P4)
	public class P4 {
        private static SymbolTable.SymbolTable symbolTable = new SymbolTable.SymbolTable();

		public static void main (String args []) {
			P4 parser = new P4(System.in);
			try {
				String result = parser.start();
                System.out.println(result);
			} catch (ParseException e) {
				System.err.println(e);
			}
		}
	}
PARSER_END(P4)

SKIP:
{
  " " | "\t" | "\n" | "\r"
}

TOKEN :
{
  <FINAL : "final">
| <INT : "int">
| <PRINT : "print">
| <IF : "if">
| <WHILE : "while">
| <ELSE : "else">
| <COMPOP : "!=" | "==" | "<=" | ">=" | ">" | "<">
| <NUMBER : ("0" | ["1"-"9"] (["0"-"9"])*)>
| <IDENT : (["a"-"z"] (["a"-"z"] | ["A"-"Z"] | ["0"-"9"])*)>
}

String PROGRAM():
{String varDecl, statement;}
{
    CONSTDECL()
    varDecl = VARDECL()
    statement = STATEMENT()
    {return varDecl + statement;}
}

void CONSTDECL() :
{}
{
    (<FINAL> <INT> CONSTZUW() CONSTLIST() ";")?
}

void CONSTZUW():
{ String constName, constValue; }
{
    <IDENT>
    {constName = token.image;}
    "="
    <NUMBER>
    {constValue = token.image;
        try {
          symbolTable.addConstant(constName, constValue);
        } catch(Exception e){
          System.err.println(e.getMessage());
          throw new Error(e);
        }
    }
}

void CONSTLIST():
{}
{
    ("," CONSTZUW())*
}

String VARDECL():
{String varDecl;}
{
    {varDecl = "";}
    (<INT>
    {varDecl = VARZUW() + VARLIST();}
    ";" {return varDecl;})?
    //EVTL VERSCHÖNERN, IDK WIE DAS MIT ? FUNKTIONIERT
   {return varDecl;}
}

String VARZUW():
{String varName, varValue; }
{
    <IDENT>
    {varName = token.image;}
    ("=")?
    (<NUMBER>
    { varValue = token.image;
        try{
            String varIndex = symbolTable.addVariable(varName);
            //varValue wird hier in einen String der Zahl als hexadezimal interpretiert umgewandelt
            return "10 " + String.format("%02x", Integer.parseInt(varValue)) + " 36 " + varIndex + " ";}
        catch(Exception e){
            System.err.println(e.getMessage());
            throw new Error(e);
        }
    })?
    { return "";}
}

String VARLIST():
{String varDecl = "";}
{
    ("," {varDecl = varDecl + VARZUW();})*
    {return varDecl;}
}

String EXPRESSION():
{String term, summe;}
{
    term = TERM()
    summe = SUMME()
    {return term + summe;}
}

String SUMME():
{String term;}
{
    {term = "";}
    (("+" | "-")
        {term = term + TERM();}
    )*
    {return term;}
}

String TERM():
{String faktor, product;}
{
    faktor = FAKTOR()
    product = PRODUCT()
    {return faktor + product;}
}

String PRODUCT():
{String term;}
{
    {term = "";}
    (("*" | "/")
        {term = term + TERM();}
    )*
    {return term;}
}


String FAKTOR():
{String number, ident, expression;}
{
    <NUMBER>
    {number = token.image;
    return String.format("%02x", Integer.parseInt(number)) + " ";}
    | <IDENT>
    {ident = token.image;
    try{
        boolean isVariable = symbolTable.isVariable(ident);
        String hashMapValue = symbolTable.getSymbol(ident);
        if(isVariable){
            return "15 " + hashMapValue + " ";
        }
        else {
            return "10 " + hashMapValue + " ";
        }
    } catch(Exception e){
            System.err.println(e.getMessage());
            throw new Error(e);
    }
    //vllt weg
    return "";
    }
    | "(" expression = EXPRESSION() ")" { return expression;}
}

String STATEMENT():
{String expression;}
{
    <PRINT> "(" expression = EXPRESSION() ")" ";"
    { return expression;}
}

String start():
{ String result; }
{
    result = PROGRAM()
    <EOF> { return result; }
}

/* Mein MiniJavaExp Code aus A1 zum Testen:
final int c = 1; int v = 2; print(c+v*v*v);
*/