/* Generated By:JavaCC: Do not edit this line. P3Constants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface P3Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FINAL = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int COMPOP = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int IDENT = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "\" \"",
    "\"final\"",
    "\"int\"",
    "\"print\"",
    "\"if\"",
    "\"while\"",
    "\"else\"",
    "<COMPOP>",
    "<NUMBER>",
    "<IDENT>",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
